# Generated by Django 3.2.9 on 2021-11-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_persona',
            fields=[
                ('pk_persona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=25, verbose_name='primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='segundo nombre')),
                ('primer_apellido', models.CharField(max_length=25, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=25, null=True, verbose_name='segundo apellido')),
                ('cui', models.CharField(max_length=25, verbose_name='cui')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('direccion', models.TextField(verbose_name='adomicilio')),
                ('telefono', models.CharField(max_length=8, verbose_name='telefono')),
                ('estado', models.BooleanField(verbose_name='activo/inactivo')),
            ],
        ),
    ]
