# Generated by Django 3.2.9 on 2021-11-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProgress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_persona',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='activo/inactivo'),
        ),
        migrations.CreateModel(
            name='tbl_usuario',
            fields=[
                ('pk_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25, verbose_name='usuario')),
                ('contrasenia', models.CharField(max_length=255, verbose_name='contraseña')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/inactivo')),
                ('fk_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appProgress.tbl_persona')),
            ],
        ),
    ]
