# Generated by Django 3.2.9 on 2021-11-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProgress', '0002_auto_20211121_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_producto',
            fields=[
                ('pk_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/inactivo')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_persona',
            name='pk_persona',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='tbl_usuario',
            name='pk_usuario',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
    ]
