# Generated by Django 3.2.9 on 2021-11-22 02:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appProgress', '0003_auto_20211121_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_detalle_ejecucion',
            fields=[
                ('pk_detalle_ejecucion', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/inactivo')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_tipo_requerimiento',
            fields=[
                ('pk_tipo_requerimiento', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/inactivo')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='fecha_fin',
            field=models.DateField(auto_now=True, verbose_name='fecha fin'),
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.CreateModel(
            name='tbl_ejecucion',
            fields=[
                ('pk_detalle_ejecucion', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/inactivo')),
                ('fk_detalle_ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProgress.tbl_detalle_ejecucion')),
            ],
        ),
    ]
