# Generated by Django 3.2.9 on 2021-11-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProgress', '0004_auto_20211121_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_requerimiento',
            fields=[
                ('pk_requerimiento', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/inactivo')),
                ('fk_ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProgress.tbl_ejecucion')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProgress.tbl_producto')),
                ('fk_tipo_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProgress.tbl_tipo_requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_asignatura',
            fields=[
                ('pk_asignatura', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(auto_now=True, verbose_name='fecha fin')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha creacion')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='fecha modificacion')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/inactivo')),
                ('estatus', models.IntegerField(default=0, verbose_name='estatus')),
                ('fk_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProgress.tbl_requerimiento')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProgress.tbl_usuario')),
            ],
        ),
    ]
