# Generated by Django 3.2.9 on 2021-12-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProgress', '0007_tbl_nota_asignatura_tbl_nota_sub_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_usuario',
            name='usuario',
            field=models.CharField(max_length=25, verbose_name='correo MSPAS'),
        ),
    ]
