# Generated by Django 3.2.9 on 2022-01-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProgress', '0008_alter_tbl_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_persona',
            name='cui',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='cui'),
        ),
        migrations.AlterField(
            model_name='tbl_persona',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='adomicilio'),
        ),
        migrations.AlterField(
            model_name='tbl_persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='tbl_persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='telefono'),
        ),
    ]
