# Generated by Django 3.2.9 on 2022-01-10 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProgress', '0009_auto_20220102_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_persona',
            name='fk_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
