# Generated by Django 3.2.9 on 2022-01-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProgress', '0010_tbl_persona_fk_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_persona',
            old_name='fk_user',
            new_name='fk_usuario',
        ),
    ]
